from datetime import datetime

from fpdf import FPDF

from tol_stack.stack import StackPath
from tol_stack.version import __version__


class StackupReport(FPDF):
    def __init__(self, stackpath: StackPath):
        super().__init__()

        self.font_name = 'helvetica'
        self.stackpath = stackpath

        # title page
        self.add_page()
        self.set_font(self.font_name, 'B', 16)
        self.cell(185, 10, f'{stackpath.name}')

        self.set_font(self.font_name, '', 12)
        self.ln(20)
        self.multi_cell(185, 10, f'Report generated by Tolerence Stack Analyzer v{__version__} on {datetime.now()}', ln=2)

        if self.stackpath.description is not None:
            self.ln(10)
            self.multi_cell(185, 10, f'{self.stackpath.description}', ln=1)

        if self.stackpath.images is not None:
            for image in self.stackpath.images:
                self.ln()
                self.image(image)


        # create a part-by-part max/min length analysis,
        # including comments, pictures, and distributions
        for part in self.stackpath.parts:
            self.add_page()
            self.set_font(self.font_name, "B", 14)
            self.cell(185, 10, f'{part.name}')

            # todo: show distribution
            # todo: show measurements and characteristics

        # todo: create a part-by-part concentricity analysis, including comments, pictures, and distributions

        self.output(f'{self.stackpath.name}.pdf')






